
import React from 'react';
import { Lightbulb, Coffee, Brain, Moon, Timer, Wind } from 'lucide-react';

const AITips: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <header>
        <h1 className="text-3xl font-bold">Daily Neuro-Insights</h1>
        <p className="text-gray-400">Personalized protocols generated by your AI Productivity Coach.</p>
      </header>

      <div className="space-y-6">
        {[
          { icon: Coffee, title: 'Optimized Caffeine Window', desc: 'Your Neuro-Fingerprint indicates a delayed adenosine peak today. Delay your first coffee until 10:30 AM for a smoother afternoon curve.', type: 'Bio-Hack' },
          { icon: Wind, title: 'Brain Refresh Session', desc: 'Detected ocular strain. Every 20 minutes, perform a 4-7-8 breathing drill for 60 seconds to reset your amygdala.', type: 'Relaxation' },
          { icon: Timer, title: 'Pomodoro Cycle: 50/10', desc: 'Current brain sharpness is high. Adjust your focus cycles to 50 minutes work, 10 minutes active rest (walking).', type: 'Productivity' },
          { icon: Moon, title: 'Blue Light Lockout', desc: 'To maximize tomorrow\'s IQ baseline, activate night filters at 8:45 PM. Magnesium Threonate supplementation recommended.', type: 'Sleep' },
        ].map((tip, i) => (
          <div key={i} className="bg-gray-900/40 border border-gray-800 hover:border-indigo-500/30 p-6 rounded-[2rem] flex items-start gap-6 transition-all group">
            <div className="p-4 bg-gray-800 rounded-2xl group-hover:bg-indigo-600/10 group-hover:text-indigo-400 transition-all">
              <tip.icon className="w-8 h-8" />
            </div>
            <div className="flex-1">
              <div className="flex justify-between items-center">
                <h3 className="text-lg font-bold">{tip.title}</h3>
                <span className="text-[10px] font-black uppercase tracking-widest px-3 py-1 bg-gray-800 rounded-full text-gray-400">{tip.type}</span>
              </div>
              <p className="text-sm text-gray-500 mt-2 leading-relaxed">{tip.desc}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default AITips;
